export const sectionPopulate = {
  on: {
    "sections.hero": { populate: ["stats", "image"] },
    "sections.client-logos": { populate: { clients: { populate: ["image"] } } },
    "sections.results": { populate: ["stats"] },
    "sections.process": { populate: ["steps"] },
    "sections.why-us": { populate: ["pillars"] },
    "sections.team": { populate: { members: { populate: ["image"] } } },
    "sections.bullet-list": { populate: ["items"] },
    "sections.numbered-steps": { populate: ["steps"] },
    "sections.faq": { populate: ["items"] },
    "sections.price-factors": { populate: ["items"] },
    "sections.service-cards": { populate: { cards: { populate: ["items"] } } },
    "sections.case-story": { populate: ["approach", "metrics", "image"] },
    "sections.prose": { populate: "*" },
    "sections.notice": { populate: "*" },
    "sections.testimonial": { populate: "*" },
    "sections.contact-cta": { populate: "*" },
    "sections.contact-form": { populate: "*" },
    "sections.case-grid": { populate: { tabs: { populate: "*" } } },
    "sections.row": { populate: "*" },
    "sections.page-index": { populate: ["articleTypes"] },
    "sections.link-list": { populate: ["items"] },
    "sections.image-slider": { populate: { slides: { populate: ["image"] } } },
    "sections.image": { populate: ["image"] },
    "sections.video": { populate: "*" },
    "sections.heading": { populate: "*" },
    "sections.button": { populate: "*" },
    "sections.divider": { populate: "*" },
    "sections.spacer": { populate: "*" },
    "sections.split": { populate: ["image"] },
    "sections.takeaways": { populate: ["items"] },
    "sections.table": { populate: ["rows"] },
    "sections.columns": { populate: "*" },
    "sections.cards": { populate: { cards: { populate: ["image"] } } },
    "sections.vacancies": { populate: { items: { populate: ["copy"] } } },
    "sections.accordion": { populate: ["items"] },
    "sections.expert": { populate: ["image"] },
    "sections.sources": { populate: ["items"] },
    "sections.gallery": { populate: { items: { populate: ["image"] } } },
    "sections.before-after": { populate: ["before", "after"] },
    "sections.reviews": { populate: ["items"] },
    "sections.location": { populate: "*" },
    "sections.map-embed": { populate: "*" },
    "sections.document": { populate: ["file"] },
    "sections.button-row": { populate: "*" },
  },
};
